version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: weather-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend-service:
    image: samarthfunde/weather-backend-image:v4
    container_name: weather-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
  
  frontend:
    image: samarthfunde/weather-frontend-image:v3
    container_name: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-service   # ‚Üê must match backend service name

volumes:
  mongo-data:
